# Generated by Django 5.1 on 2024-09-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'NIKE'), (2, 'ADIDAS'), (3, 'PUMA'), (4, 'NEW BALANCE'), (5, 'UMBRO'), (6, 'KAPPA'), (7, 'VOLT'), (8, 'MIZUNO'), (9, 'UNDER ARMOUR')])),
                ('time', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('tipo', models.SmallIntegerField(choices=[(1, 'HOME'), (2, 'AWAY'), (3, 'THIRD'), (4, 'SPECIAL')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='camisa/fotos')),
                ('tamanho', models.SmallIntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG')])),
            ],
        ),
    ]
