# Generated by Django 5.1 on 2024-10-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camisa',
            name='tamanho',
            field=models.SmallIntegerField(choices=[(1, 'P'), (2, 'M'), (3, 'G'), (4, 'GG')]),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'HOME'), (2, 'AWAY'), (3, 'THIRD'), (4, 'SPECIAL')]),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='marca',
            field=models.SmallIntegerField(choices=[(1, 'NIKE'), (2, 'ADIDAS'), (3, 'PUMA'), (4, 'NEW BALANCE'), (5, 'UMBRO'), (6, 'KAPPA'), (7, 'VOLT'), (8, 'MIZUNO'), (9, 'UNDER ARMOUR')]),
        ),
    ]
