# Generated by Django 5.1.1 on 2024-12-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisa', '0003_alter_camisa_tamanho_alter_camisa_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camisa',
            name='marca',
            field=models.SmallIntegerField(choices=[(5, 'UMBRO'), (4, 'NEW BALANCE'), (7, 'VOLT'), (9, 'UNDER ARMOUR'), (2, 'ADIDAS'), (3, 'PUMA'), (1, 'NIKE'), (8, 'MIZUNO'), (6, 'KAPPA')]),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='tamanho',
            field=models.SmallIntegerField(choices=[(4, 'GG'), (2, 'M'), (3, 'G'), (1, 'P')]),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='tipo',
            field=models.SmallIntegerField(choices=[(2, 'AWAY'), (1, 'HOME'), (4, 'SPECIAL'), (3, 'THIRD')]),
        ),
    ]
